---
- debug:
    msg: "oah-reset"

#remove oah-usage

#remove oah-shell

#remove oah-users

#check and install oah-users

#check and install oah-shell

#check and install oah-usage

#display ansible setup
