---
- debug:
    msg: "oah-validate"
# check oah users exists

# check if oah shell exists

# check if oah version

# check oah status

# check oah usage cron installed

# display last usage message and update

# display ansible status
